#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set some vars
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"
JOBNAME="${1:-''}"
LOGFILE="${SCRIPT_PATH}/log/cron.$(date +%F).log"
MAILTO="julian.gieseke@gmail.com"

# some checks
[ ! -f "${LOGFILE}" ] && touch ${LOGFILE}

# run backup job
./run ${JOBNAME} > >(tee -a ${LOGFILE}) 2> >(tee -a ${LOGFILE} >&1) \
  || echo -e "Subject: ❌ Error on Cronjob '${JOBNAME}' at $(date)\n\n$(tac ${LOGFILE} | grep -m1 -B50000 🚛 | tac | tail -n 100)" | ssmtp ${MAILTO} \
  || tail -n 100 ${LOGFILE}
