#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

FORCE_LOCAL=${FORCE_LOCAL:-''}
FORCE_REMOTE=${FORCE_REMOTE:-''}
RSYNCOPTS="${RSYNCOPTS:-""}"

# set some vars
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"
JOBNAME="${1:-''}"
LOGFILE="${SCRIPT_PATH}/log/cron.$(date +%F).log"
MAILTO="julian.gieseke@gmail.com"

# some checks
[ ! -f "${LOGFILE}" ] && touch ${LOGFILE}

# run backup job
${SCRIPT_PATH}/run ${JOBNAME} > >(tee -a ${LOGFILE}) 2> >(tee -a ${LOGFILE} >&1) \
  || echo -e "Subject: ❌ Error on Cronjob '${JOBNAME}' at $(date)\n\n$(tail -n 20 ${LOGFILE})" | ssmtp ${MAILTO} \
  || tail -n 20 ${LOGFILE}
