#!/usr/bin/env bash

echo Disk Stats
echo "/"
if [ $(btrfs filesystem show / > /dev/null 2>&1;echo $?) -eq 0 ]
then
  btrfs filesystem df /mnt/boot.disk/
  btrfs filesystem du -s /mnt/boot.disk/
else
  df -hl /
  du -sh /
  hddtemp -w /dev/sda
fi
echo
echo "data.disk"
btrfs filesystem df /mnt/data.disk/
btrfs filesystem du -s /mnt/data.disk/
echo
echo "backups.disk"
btrfs filesystem df /mnt/backups.disk/
btrfs filesystem du -s /mnt/backups.disk/
echo
echo Mounts "(Count: $(mount | grep /mnt | wc -l))"
find /mnt -maxdepth 1 -mindepth 1 -type d -exec btrfs fi show '{}' >/dev/null ';'
mount | grep /mnt | cut -d \( -f1
