#!/usr/bin/env bash

set -e

# debug
DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set SCRIPT_PATH, used for external refs
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"

echo Status Report for $(hostname)
echo ==============================================
echo
cat /var/run/motd.dynamic
echo ==============================================
echo
echo Disk Temp
hddtemp -w /dev/sd?
echo
echo Disk Stats
echo "/"
[ $(btrfs filesystem show / > /dev/null 2>&1;echo $?) -eq 0 ] && btrfs filesystem df /mnt/boot.disk/ || df -hl /
[ $(btrfs filesystem show / > /dev/null 2>&1;echo $?) -eq 0 ] && btrfs filesystem du -s /mnt/boot.disk/ || du -sh /
echo
echo "data.disk"
btrfs filesystem df /mnt/data.disk/
btrfs filesystem du -s /mnt/data.disk/
echo
echo "backups.disk"
btrfs filesystem df /mnt/backups.disk/
btrfs filesystem du -s /mnt/backups.disk/
echo
echo Mounts "(Count: $(mount | grep /mnt | wc -l))"
find /mnt -maxdepth 1 -mindepth 1 -type d -exec btrfs fi show '{}' >/dev/null ';'
mount | grep /mnt | cut -d \( -f1

#logfiles
find ${SCRIPT_PATH} -maxdepth 1 -type f -name '*.log' | \
  while read LOGFILE
  do
    echo
    echo
    echo ==============================================
    echo
    echo Last 100 lines of $(basename ${LOGFILE})
    tail -n 100 ${LOGFILE}
  done
