#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set SCRIPT_PATH
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"

SUBSCRIPT="${1:-''}"
LOGFILE="${SUBSCRIPT}.log"

MAILTO="julian.gieseke@gmail.com"

[ -z "${SUBSCRIPT}" ] && echo "ERROR: No \$SUBSCRIPT given" && exit 1;

[ ! -f "${LOGFILE}" ] && touch ${LOGFILE}

${SUBSCRIPT} 1>>${LOGFILE} 2>>${LOGFILE} \
  || echo -e "Subject: ❌ Error on Job '$(basename ${SUBSCRIPT})'\n\n$(tac ${LOGFILE} | grep -m1 -B500 🚛)" | ssmtp ${MAILTO} \
  || tail -n 100 ${LOGFILE}
