#!/usr/bin/env bash

# sets $CRONTYPE
source ${SCRIPT_PATH}/inc/crontype /mnt/volume/backups
# sets $KEEPDAYS
source ${SCRIPT_PATH}/inc/keepdays ${CRONTYPE}

# create snapshot
${SCRIPT_PATH}/bin/snapshot /mnt/volume/backups ${CRONTYPE} ${KEEPDAYS}

# print footer
echo Done.