#!/usr/bin/env bash

# sets $CRONTYPE
source ${SCRIPT_PATH}/inc/crontype /mnt/volume/resilio
# sets $KEEPDAYS
source ${SCRIPT_PATH}/inc/keepdays ${CRONTYPE}

# create snapshot
${SCRIPT_PATH}/bin/snapshot /mnt/volume/resilio ${CRONTYPE} ${KEEPDAYS}

if [ ${CRONTYPE} != 'hourly' ]
then
  ${SCRIPT_PATH}/bin/backup /mnt/volume/resilio /mnt/volume/backups/
fi

# print footer
echo Done.