#!/usr/bin/env bash

# sets $CRONTYPE
source ${SCRIPT_PATH}/inc/crontype /mnt/volume/speichersee
# sets $KEEPDAYS
source ${SCRIPT_PATH}/inc/keepdays ${CRONTYPE}

# create snapshot
${SCRIPT_PATH}/bin/snapshot /mnt/volume/speichersee ${CRONTYPE} ${KEEPDAYS}

if [ ${CRONTYPE} != 'hourly' ]
then
  ${SCRIPT_PATH}/bin/backup /mnt/volume/speichersee /mnt/volume/backups/
  /usr/sbin/vpnc hhs
  ${SCRIPT_PATH}/bin/backup /mnt/volume/speichersee speichersee@192.168.187.11:/mnt/volume/
  /usr/sbin/vpnc-disconnect
fi

# print footer
echo Done.