#!/usr/bin/env bash

# set SCRIPT_PATH
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"

#logfiles
find ${SCRIPT_PATH}/log -mindepth 1 -maxdepth 1 -type f | \
  while read LOGFILE
  do
    echo Last line of $(basename ${LOGFILE})
    tail -n 1 ${LOGFILE}
    echo;
  done

#logfiles
find ${SCRIPT_PATH}/log -mindepth 1 -maxdepth 1 -type f | \
  while read LOGFILE
  do
    echo
    echo
    echo ==============================================
    echo
    echo Last 100 lines of $(basename ${LOGFILE})
    tail -n 100 ${LOGFILE}
  done