#!/usr/bin/env bash

# no set -e here, we want to run all subscript, even if one fails!

BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

if [ "$(hostname)" == "Datenteich" ]
then
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-snapshots /mnt/data.disk/resilio.snapshots /mnt/backups.disk/resilio.snapshots
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-snapshots /mnt/data.disk/datenteich.snapshots /mnt/backups.disk/datenteich.snapshots
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-snapshots /mnt/boot.disk/rootfs.snapshots /mnt/backups.disk/rootfs.snapshots
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-remote /mnt/data.disk/datenteich/ datenteich@192.168.152.11:/mnt/backups.disk/datenteich/ /mnt/backups.disk/datenteich.backups/ bms
fi

if [ "$(hostname)" == "Speichersee" ]
then
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-snapshots /mnt/data.disk/speichersee.snapshots /mnt/backups.disk/speichersee.snapshots
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/retry ${BASE_PATH}/bin/backup-remote /mnt/data.disk/speichersee/ speichersee@192.168.187.11:/mnt/backups.disk/speichersee/ /mnt/backups.disk/speichersee.backups/ hhs
fi
