#!/usr/bin/env bash

# no set -e here, we want to run all subscript, even if one fails!

PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd ../bin && pwd):${PATH}"

log snapshot-create /mnt/data.disk/resilio /mnt/data.disk/resilio.snapshots
log snapshot-cleanup /mnt/data.disk/resilio.snapshots

if [ "$(hostname)" == "Datenteich" ]
then
    log snapshot-create /mnt/data.disk/datenteich /mnt/data.disk/datenteich.snapshots
    log snapshot-create /mnt/boot.disk/rootfs /mnt/boot.disk/rootfs.snapshots

    log snapshot-cleanup /mnt/data.disk/datenteich.snapshots
    log snapshot-cleanup /mnt/boot.disk/rootfs.snapshots

    {
        log retry backup-snapshots /mnt/data.disk/resilio.snapshots /mnt/backups.disk/resilio.snapshots
        log retry backup-snapshots /mnt/data.disk/datenteich.snapshots /mnt/backups.disk/datenteich.snapshots
        log retry backup-snapshots /mnt/boot.disk/rootfs.snapshots /mnt/backups.disk/rootfs.snapshots
    } &
    SNAP_PID=$!

    {
        log retry backup-remote $(find /mnt/data.disk/datenteich.snapshots/ -maxdepth 1 -type d | tail -n1)/ datenteich@speichersee.fritz.box:/mnt/backups.disk/datenteich/ /mnt/backups.disk/datenteich.backups bms
        log retry backup-remote $(find /mnt/data.disk/datenteich.snapshots/ -maxdepth 1 -type d | tail -n1)/ datenteich@aussenbecken.fritz.box:/volume1/datenteich/datenteich/ /volume1/datenteich/datenteich.backups bss
    } &
    REMOTE_PID=$!

fi

if [ "$(hostname)" == "Speichersee" ]
then
    log snapshot-create /mnt/data.disk/speichersee /mnt/data.disk/speichersee.snapshots

    log snapshot-cleanup /mnt/data.disk/speichersee.snapshots

    {
        log retry backup-snapshots /mnt/data.disk/speichersee.snapshots /mnt/backups.disk/speichersee.snapshots
    } &
    SNAP_PID=$!

    {
        log retry backup-remote $(find /mnt/data.disk/speichersee.snapshots/ -maxdepth 1 -type d | tail -n1)/ speichersee@datenteich.fritz.box:/mnt/backups.disk/speichersee/ /mnt/backups.disk/speichersee.backups hhs
        log retry backup-remote $(find /mnt/data.disk/speichersee.snapshots/ -maxdepth 1 -type d | tail -n1)/ speichersee@aussenbecken.fritz.box:/volume1/speichersee/speichersee/ /volume1/speichersee/speichersee.backups bss
    } &
    REMOTE_PID=$!

    
fi

function clean_up {
    trap - EXIT
    kill $SNAP_PID >/dev/null 2>/dev/null
    kill $REMOTE_PID >/dev/null 2>/dev/null
}

trap clean_up EXIT SIGHUP SIGINT SIGTERM

wait $SNAP_PID $REMOTE_PID

report
