#!/usr/bin/env bash

# no set -e here, we want to run all subscript, even if one fails!

PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd ../bin && pwd):${PATH}"

log snapshot-create /mnt/data.disk/resilio /mnt/data.disk/resilio.snapshots

if [ "$(hostname)" == "Datenteich" ]
then
    log snapshot-create /mnt/data.disk/datenteich /mnt/data.disk/datenteich.snapshots
    log snapshot-create /mnt/boot.disk/rootfs /mnt/boot.disk/rootfs.snapshots
fi

if [ "$(hostname)" == "Speichersee" ]
then
    log snapshot-create /mnt/data.disk/speichersee /mnt/data.disk/speichersee.snapshots
fi
