#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

err_report() {
  echo "errexit on line $(caller)" >&2
}
trap err_report ERR

BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

MAILTO="julian.gieseke@gmail.com"
MAILBODY="${BASE_PATH}/reports/mail.txt"

# reset file contents with subject & motd
echo -e "Todays System Report for $(hostname)\n\n=======================================\n" | tee ${MAILBODY}
cat /var/run/motd.dynamic | tee -a ${MAILBODY}
echo -e "=======================================\n" | tee -a ${MAILBODY}

# get the last lines of cron logfiles
echo -e "Exitcodes in Logfiles:\n" | tee -a ${MAILBODY}
find ${BASE_PATH}/log -mindepth 1 -maxdepth 1 -type f -name "*.log" | \
  while read LOGFILE
  do
    echo -n "$(basename --suffix=.log "${LOGFILE}"): " | tee -a ${MAILBODY}
    { [ $(echo "exitcode 0" | grep 'exitcode 0' | wc -l) -eq 1 ] && echo ✅ || echo ❌; } | tee -a ${MAILBODY}
  done

echo;
echo -e ======================================= "\n" | tee -a ${MAILBODY}

${BASE_PATH}/reports/disks.$(hostname | tr '[:upper:]' '[:lower:]') | tee -a ${MAILBODY}

echo -e ======================================= "\n" | tee -a ${MAILBODY}


# send mail with all remaining logfiles as attachements
cat ${MAILBODY} | mutt -s "System Report for $(hostname)" -a ${BASE_PATH}/log/*.log -- $MAILTO

# delete old logs: 
find ${BASE_PATH}/log -name '*.log' | \
  while read LOGFILE
  do
    echo -n "Deleting old logfile $(basename $LOGFILE)… "
    rm "$LOGFILE"
    echo "done."
  done