#!/usr/bin/env bash

# no set -e here, we want to run all subscript, even if one fails!

BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/snapshot-cleanup /mnt/data.disk/resilio.snapshots

if [ "$(hostname)" == "Datenteich" ]
then
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/snapshot-cleanup /mnt/data.disk/datenteich.snapshots
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/snapshot-cleanup /mnt/boot.disk/rootfs.snapshots
fi

if [ "$(hostname)" == "Speichersee" ]
then
    ${BASE_PATH}/bin/mail-error ${BASE_PATH}/bin/snapshot-cleanup /mnt/data.disk/speichersee.snapshots
fi