#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set BASE_PATH
BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

# lockfile and traps
JOBNAME="debug"
source ${BASE_PATH}/inc/header

#################################################

#debug stuff 
echo "OK to stdout"
echo "ERROR to stderr" 1>&2; 

sleep 3

exit 1


echo "✅ Successfully completed after $(displaytime ${SECONDS}) at $(date)."
