#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set BASE_PATH
BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

# lockfile and traps
JOBNAME='resilio'
source ${BASE_PATH}/inc/header

#config
SRC='/mnt/data.disk/resilio/'
DST_SNAP='/mnt/data.disk/resilio.snapshots/'
DST_SEND='/mnt/backups.disk/resilio.snapshots/'

# gets $JOBNAME
# sets $JOBTYPE
source ${BASE_PATH}/inc/jobtype

# gets $JOBTYPE
# sets $KEEPDAYS
source ${BASE_PATH}/inc/keepdays

#################################################

# create snapshot
${BASE_PATH}/bin/snapshot-create ${SRC} ${DST_SNAP} ${JOBTYPE}

# cleanup snapshots
${BASE_PATH}/bin/snapshot-cleanup ${DST_SNAP} ${JOBTYPE} ${KEEPDAYS}

# run backups, if not hourly
if [ "$(hostname)" == "Datenteich" ] && [[ -n "${FORCE_LOCAL}" || ${JOBTYPE} != 'hourly' ]]
then
  ${BASE_PATH}/bin/retry-local ${JOBTYPE} ${SRC} ${DST_SNAP} ${DST_SEND}
fi
