#!/usr/bin/env bash

set -e

DEBUG=${DEBUG:-''}
[ -n "${DEBUG}" ] && set -x

# set BASE_PATH
BASE_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && cd .. && pwd)"

# lockfile and traps
JOBNAME='rootfs'
source ${BASE_PATH}/inc/header

#config
SRC='/mnt/boot.disk/rootfs/'
DST_SNAP='/mnt/boot.disk/rootfs.snapshots/'
DST_SEND='/mnt/backups.disk/rootfs.snapshots/'

# gets $JOBNAME
# sets $JOBTYPE
source ${BASE_PATH}/inc/jobtype

# gets $JOBTYPE
# sets $KEEPDAYS
source ${BASE_PATH}/inc/keepdays

#################################################

# create snapshot
${BASE_PATH}/bin/snapshot-create ${SRC} ${DST_SNAP} ${JOBTYPE}

# cleanup snapshots
${BASE_PATH}/bin/snapshot-cleanup ${DST_SNAP} ${JOBTYPE} ${KEEPDAYS}

# run backups, if not hourly
[ ${JOBTYPE} != 'hourly' ] && ${BASE_PATH}/bin/retry-local ${JOBTYPE} ${SRC} ${DST_SNAP} ${DST_SEND}

#################################################

echo "✅ Successfully completed after $(displaytime ${SECONDS}) at $(date)."
