#!/usr/bin/env bash

[ -z "${CRONNAME}" ] && ( echo "ERROR: No \$CRONNAME given." 1>&2; exit 1 )

#################################################
# setup output & traps
LOGPREFIX="${CRONNAME} %T"
LOGFILE="/mnt/cron.log"

# ref https://stackoverflow.com/a/19279694
# the `grep -v '^At subvol'` hack is necessary because `btrfs receive` has no --quiet flag but I want to suppress that message :(
exec > >(ts "${LOGPREFIX}" | tee -a ${LOGFILE}) 2> >(grep -v '^At subvol' | ts "${LOGPREFIX} ❌" | tee -a ${LOGFILE} >&2)

lockfile -60 -r50  "/mnt/cron.${CRONNAME}.lock"
function trap_cleanup {
  rm -f "/mnt/cron.${CRONNAME}.lock"
}
trap "trap_cleanup" EXIT

echo "🚦 Starting ($(date))"
