#!/usr/bin/env bash

if [ -n "${JOBTYPE}" ]
then
  echo "Manually set \$JOBTYPE to '${JOBTYPE}'"
  return
fi

JOBTYPE='hourly'

# only allow type daily if job runs at nighttime
# last daily snapshot should be older then 10 hours to prevent multiple runs per night
if [ $(find "${DST_SNAP%/}/" -maxdepth 1 -type d -name "*-daily" -cmin -1080 | wc -l) -eq 0 ]
then
  JOBTYPE='daily'
fi

# only allow type weekly if job runs at nighttime
if [ $(find "${DST_SNAP%/}/" -maxdepth 1 -type d -name "*-weekly" -ctime -7 | wc -l) -eq 0 ]
then
  JOBTYPE='weekly'
fi

# only allow type monthly if job runs at nighttime
if [ $(find "${DST_SNAP%/}/" -maxdepth 1 -type d -name "*-monthly" -ctime -28 | wc -l) -eq 0 ]
then
  JOBTYPE='monthly'
fi

if [ "${JOBTYPE}" != 'hourly' ] && [ $(date +%H) -gt 5 ]
then
  echo "Deferring type '${JOBTYPE}' until tonight."
  JOBTYPE='hourly'
fi
