#!/usr/bin/env bash

KEEPDAYS=${KEEPDAYS:-0}

if [ ${KEEPDAYS} -ne 0 ]
then
  echo "📝 Manually set \$KEEPDAYS to '${KEEPDAYS}'"
  return
fi

case ${CRONTYPE} in
  hourly)
    KEEPDAYS=1
    ;;
  daily)
    KEEPDAYS=30
    ;;
  weekly)
    KEEPDAYS=90
    ;;
  monthly)
    KEEPDAYS=360
    ;;
esac
